# Generated by Django 6.0.2 on 2026-07-16 17:43

import django.db.models.deletion
import signatures.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(db_index=True, default=signatures.models.generate_short_id, editable=False, help_text='A unique 8-character hex ID for public verification.', max_length=8, unique=True)),
                ('document_hash', models.CharField(help_text='The JCS canonical SHA-256 hash of the normalized document content at the moment of signing. Matches DocumentData.content_hash.', max_length=64)),
                ('cryptographic_signature', models.TextField(help_text='The RSA-PSS signature over document_hash.')),
                ('public_key', models.TextField(blank=True, help_text='PEM public key used to verify the cryptographic signature.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document signature',
                'verbose_name_plural': 'document signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id_used', models.CharField(help_text='The ID the user attempted to look up.', max_length=20)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('tampered', 'Tampered'), ('not_found', 'Not Found'), ('error', 'Error')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='signatures.documentsignature')),
            ],
            options={
                'verbose_name': 'public verification log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
